name: CI-CD Build and Deploy Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Build Docker image from Source Code folder
      - name: Build Docker image
        run: |
          docker build -t frontend-app \
          "./CI-CD Pipeline Project/Source Code"

      # Step 3: Deploy to EC2 using SSH
      - name: Deploy Docker image to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker rmi frontend-app || true

            cd ~/CI-CD || mkdir -p ~/CI-CD
            cd ~/CI-CD

            rm -rf app || true
            git clone https://github.com/NarenMK-25/devops.git
            cd app/CI-CD\ Pipeline\ Project/Source\ Code

            docker build -t frontend-app .
            docker run -d -p 80:80 --name frontend-app frontend-app
